server:
  port: 8050
spring:
  application:
    name: account
  datasource:
    url: jdbc:mysql://localhost:3306/orderingsystem?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.kyx.entity